eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9093/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
     zone: ABC
     lilizhou: BBC
spring:
  application:
    name: student-server
